### ISSUE TITLE
not working, invalid key name

### ISSUE THREAD

**Issue by c6matose** [SincerelyFair/valorant-triggerbot#1]
![image](https://user-images.githubusercontent.com/44951034/198592510-6dd4742f-9ba3-4dac-9f0d-9c823f910553.png)
hello, i get this error when i run the script, running as admin doesn't change anything, is there any way to fix this? thank you

**Comment by SincerelyFair** [comment]
replace configs in data folder by the updated ones

**Comment by SincerelyFair** [comment]
fixed lmk if it still doesn't work

**Comment by c6matose** [comment]
it works now, thank you for helping :)
