### ISSUE TITLE
Hi can you update it ?

### ISSUE THREAD

**Issue by Eren207** [SincerelyFair/valorant-triggerbot#2]
Hi can you Update it from the Website the old doesn't work like the new

**Comment by SincerelyFair** [comment]
it's literally a free cracked release of the same paid one in the website

**Comment by Eren207** [comment]
Why it is lila and without key¿

**Comment by SincerelyFair** [comment]
> Why it is lila and without key¿

you can change the colours in the theme tab to the ones u like, and as i said it has no key because it's a crack of the loader so u can use it for free
